# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test --passWithNoTests
    - run: npm run release ${{ github.run_number }}
    
    # - name: Push release to github
    #   id: create_release
    #   uses: actions/create_release@v1
    #   #env:
    #   #  GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.run_nmber }}
    #     draft: false
    # - uses: actions/upload_release@v1
    #   #env:
    #   #  GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     asset_path: "releases/pwgen_react_${{ github_run_number }}.zip"
    # - uses: eregon/publish_release@v1
    #   #env:
    #   #  GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
    #   id: ${{ steps.create_release.outputs.id }}
